# Generated by Django 3.1.2 on 2021-06-17 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(default='NOMBRE COMPLETO', max_length=100)),
                ('rut_cliente', models.CharField(default='RUT', max_length=11)),
                ('direccion', models.CharField(default='DIRECCION', max_length=100)),
                ('nro_venta', models.CharField(default='NUMERO VENTA', max_length=11)),
                ('tipo_venta', models.CharField(default='TIPO VENTA', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_despacho', models.CharField(default='NUMERO DESPACHO', max_length=5)),
                ('conductor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Crud.conductor')),
                ('venta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Crud.venta')),
            ],
        ),
    ]
