# Generated by Django 3.1.2 on 2021-06-19 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crud', '0002_despacho_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='ESTADO', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_compra',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado_compra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Crud.estadocompra'),
        ),
    ]
