# Generated by Django 3.2 on 2021-07-10 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crud', '0004_direccion_postventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='lat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='long',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
